name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Cache Clash_Core
        id: cache-Clash_Core
        uses: actions/cache@v4
        with:
          path: clash
          key: Clash_Core
          restore-keys: |
            Clash_Core

      - name: Download Clash_Core
        if: steps.cache-Clash_Core.outputs.cache-hit != 'true'
        run: |
          curl -L -o clash-linux-amd64.tar.gz https://raw.githubusercontent.com/vernesong/OpenClash/core/master/meta/clash-linux-amd64.tar.gz
          tar -zxvf clash-linux-amd64.tar.gz

      - name: Cache GEOIP
        id: cache-GEOIP
        uses: actions/cache@v4
        with:
          path: geoip.metadb
          key: GEOIP
          restore-keys: |
            GEOIP

      - name: Download GEOIP
        if: steps.cache-GEOIP.outputs.cache-hit != 'true'
        run: |
          curl -L -o geoip.metadb https://github.com/Hackl0us/GeoIP2-CN/raw/release/Country.mmdb

      - name: Cache subconverter
        id: cache-subconverter
        uses: actions/cache@v4
        with:
          path: subconverter.tar.gz
          key: subconverter
          restore-keys: |
            subconverter

      - name: Download subconverter
        if: steps.cache-subconverter.outputs.cache-hit != 'true'
        run: |
          curl -L -o subconverter.tar.gz https://github.com/tindy2013/subconverter/releases/download/v0.9.0/subconverter_linux64.tar.gz

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Start web server
        run: |
          sed -i 's|https://raw.githubusercontent.com/PKC278/clash/main|http://localhost:8000|g' "config.ini"
          python -m http.server 8000 &

      - name: Download config.yaml
        run: |
          tar -zxf subconverter.tar.gz
          subconverter/subconverter > /dev/null 2>&1 &
          sleep 2
          curl -L -o config.yaml "http://localhost:25500/sub?target=clash&url=ss%3A%2F%2FYWVzLTI1Ni1jZmI6eXlvdXNlcnBhc3N3b3JkQDEyNy4wLjAuMTo4Mzg4&config=http%3A%2F%2Flocalhost%3A8000%2Fconfig.ini"

      - name: Test
        run: |
          ./clash -d ./ &
          CLASH_PID=$!
          sleep 2
          if ps -p $CLASH_PID > /dev/null; then
              exit 0
          else
              exit 1
          fi
  Release:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Replace strings in config.ini
        run: |
          sed -i 's/PKC278\/clash\/main/PKC278\/clash\/release/g' config.ini
      - name: Push to release branch
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git stash
          git switch -C release
          git stash pop
          git add config.ini
          git commit -m "Update config.ini for release"
          git push -f origin release
